- name: test leveldb cache
  hosts: all
  gather_facts: True
  tasks:
    - setup:
    - set_fact:
        message: hello leveldb
    - debug:
        var: message
    - debug:
        var: ansible_local.data.data1
    - pause:


